---
engines:
  golint:
    enabled: true
  gofmt:
    enabled: true
  govet:
    enabled: true
    config: 
  fixme:
    enabled: true
  markdownlint:
    enabled: true
ratings:
  paths: []
exclude_paths: []
